/**
 * Public package entry — Base UI Solid port.
 *
 * Upstream pin: `@base-ui/react@1.7.0` (see `UPSTREAM.md`).
 *
 * @example
 * ```tsx
 * import { Button, version } from "@script-augur/base-ui-solid"
 * // or: import { Button } from "@script-augur/base-ui-solid/button"
 *
 * <Button onClick={() => {}}>Save</Button>
 * ```
 */

/** Package semver string for the current build (from `package.json` at build time). */
export const version: string = __PACKAGE_VERSION__

/** npm package name (from `package.json` at build time). */
export const PACKAGE_NAME: string = __PACKAGE_NAME__

export { Button, ButtonDataAttributes } from './button'
export { Separator, SeparatorDataAttributes } from './separator'
export { Toggle, ToggleDataAttributes } from './toggle'
export {
  ToggleGroup,
  ToggleGroupDataAttributes,
  ToggleGroupContext,
  useToggleGroupContext,
} from './toggle-group'
export {
  Collapsible,
  CollapsibleRoot,
  CollapsibleRootDataAttributes,
  CollapsibleRootContext,
  useCollapsibleRootContext,
  CollapsibleTrigger,
  CollapsibleTriggerDataAttributes,
  CollapsiblePanel,
  CollapsiblePanelDataAttributes,
  CollapsiblePanelCssVars,
} from './collapsible'
export {
  Accordion,
  AccordionRoot,
  AccordionRootDataAttributes,
  AccordionRootContext,
  useAccordionRootContext,
  AccordionItem,
  AccordionItemDataAttributes,
  AccordionItemContext,
  useAccordionItemContext,
  AccordionHeader,
  AccordionHeaderDataAttributes,
  AccordionTrigger,
  AccordionTriggerDataAttributes,
  AccordionPanel,
  AccordionPanelDataAttributes,
  AccordionPanelCssVars,
} from './accordion'
export {
  Tabs,
  TabsRoot,
  TabsRootDataAttributes,
  TabsRootContext,
  useTabsRootContext,
  TabsList,
  TabsListDataAttributes,
  TabsListContext,
  useTabsListContext,
  TabTrigger,
  TabTriggerDataAttributes,
  TabsPanel,
  TabsPanelDataAttributes,
  TabsIndicator,
  TabsIndicatorDataAttributes,
  TabsIndicatorCssVars,
} from './tabs'
export {
  Progress,
  ProgressRoot,
  ProgressRootDataAttributes,
  ProgressRootContext,
  useProgressRootContext,
  ProgressTrack,
  ProgressTrackDataAttributes,
  ProgressIndicator,
  ProgressIndicatorDataAttributes,
  ProgressLabel,
  ProgressLabelDataAttributes,
  ProgressValue,
  ProgressValueDataAttributes,
} from './progress'
export {
  Meter,
  MeterRoot,
  MeterRootContext,
  useMeterRootContext,
  MeterTrack,
  MeterIndicator,
  MeterLabel,
  MeterValue,
} from './meter'
export {
  Avatar,
  AvatarRoot,
  AvatarRootContext,
  useAvatarRootContext,
  AvatarImage,
  AvatarImageDataAttributes,
  AvatarFallback,
} from './avatar'
export {
  ScrollArea,
  ScrollAreaRoot,
  ScrollAreaRootContext,
  useScrollAreaRootContext,
  ScrollAreaRootCssVars,
  ScrollAreaRootDataAttributes,
  ScrollAreaViewport,
  ScrollAreaViewportContext,
  useScrollAreaViewportContext,
  ScrollAreaViewportCssVars,
  ScrollAreaViewportDataAttributes,
  ScrollAreaScrollbar,
  ScrollAreaScrollbarContext,
  useScrollAreaScrollbarContext,
  ScrollAreaScrollbarCssVars,
  ScrollAreaScrollbarDataAttributes,
  ScrollAreaContent,
  ScrollAreaContentDataAttributes,
  ScrollAreaThumb,
  ScrollAreaThumbDataAttributes,
  ScrollAreaCorner,
} from './scroll-area'
export {
  Portal,
  PortalContext,
  usePortalContext,
  isPortalContainer,
  resolvePortalContainer,
} from './portal'
export {
  Field,
  FieldRoot,
  FieldRootDataAttributes,
  FieldLabel,
  FieldLabelDataAttributes,
  FieldDescription,
  FieldDescriptionDataAttributes,
  FieldError,
  FieldErrorDataAttributes,
  FieldControl,
  FieldControlDataAttributes,
  FieldValidity,
  FieldItem,
  FieldItemDataAttributes,
  FieldItemContext,
  useFieldItemContext,
} from './field'
export {
  FormContext,
  DEFAULT_FORM_CONTEXT,
  useFormContext,
} from './internals/form-context'
export {
  LabelableProvider,
  LabelableContext,
  useLabelableContext,
  createLabel,
  createLabelableId,
  createAriaLabelledBy,
} from './internals/labelable-provider'
export {
  FieldRootContext,
  DEFAULT_FIELD_ROOT_CONTEXT,
  useFieldRootContext,
} from './internals/field-root-context'
export {
  Fieldset,
  FieldsetRoot,
  FieldsetRootContext,
  useFieldsetRootContext,
  FieldsetLegend,
} from './fieldset'
export { Form } from './form'
export { Input, InputDataAttributes } from './input'
export {
  Dialog,
  DialogRoot,
  DialogRootContext,
  useDialogRootContext,
  DialogTrigger,
  DialogTriggerDataAttributes,
  DialogPortal,
  DialogPortalContext,
  useDialogPortalContext,
  DialogBackdrop,
  DialogViewport,
  DialogViewportDataAttributes,
  DialogPopup,
  DialogPopupDataAttributes,
  DialogPopupCssVars,
  DialogTitle,
  DialogDescription,
  DialogClose,
} from './dialog'
export {
  AlertDialog,
  AlertDialogRoot,
  AlertDialogRootContext,
  useAlertDialogRootContext,
  AlertDialogTrigger,
  AlertDialogTriggerDataAttributes,
  AlertDialogPortal,
  AlertDialogPortalContext,
  useAlertDialogPortalContext,
  AlertDialogBackdrop,
  AlertDialogViewport,
  AlertDialogViewportDataAttributes,
  AlertDialogPopup,
  AlertDialogPopupDataAttributes,
  AlertDialogPopupCssVars,
  AlertDialogTitle,
  AlertDialogDescription,
  AlertDialogClose,
} from './alert-dialog'
export {
  Popover,
  PopoverRoot,
  PopoverRootContext,
  usePopoverRootContext,
  PopoverTrigger,
  PopoverTriggerDataAttributes,
  PopoverPortal,
  PopoverPortalContext,
  usePopoverPortalContext,
  PopoverPositioner,
  PopoverPositionerContext,
  usePopoverPositionerContext,
  PopoverPositionerCssVars,
  PopoverPositionerDataAttributes,
  PopoverPopup,
  PopoverPopupCssVars,
  PopoverPopupDataAttributes,
  PopoverArrow,
  PopoverArrowDataAttributes,
  PopoverBackdrop,
  PopoverBackdropDataAttributes,
  PopoverTitle,
  PopoverDescription,
  PopoverClose,
  PopoverViewport,
  PopoverViewportCssVars,
  PopoverViewportDataAttributes,
  createPopoverHandle,
  PopoverHandle,
} from './popover'
export {
  createControlled,
  createChangeEventDetails,
  createGenericEventDetails,
  REASONS,
  createRender,
  splitRenderProps,
  useRender,
  mergeAttrs,
  dataAttr,
  callHandler,
  useButton,
  useFocusableWhenDisabled,
  useFloating,
  offset,
  flip,
  shift,
  arrow,
  autoUpdate,
  computePosition,
  createFocusTrap,
  createDismiss,
  createScrollLock,
  DirectionProvider,
  useDirection,
  DirectionContext,
} from './internals'

export type { ButtonProps, ButtonState } from './button'
export type { Orientation, SeparatorProps, SeparatorState } from './separator'
export type {
  ToggleChangeEventDetails,
  ToggleChangeEventReason,
  ToggleProps,
  ToggleState,
} from './toggle'
export type {
  ToggleGroupChangeEventDetails,
  ToggleGroupChangeEventReason,
  ToggleGroupContextValue,
  ToggleGroupProps,
  ToggleGroupState,
} from './toggle-group'
export type {
  CollapsibleRootChangeEventDetails,
  CollapsibleRootChangeEventReason,
  CollapsibleRootContextValue,
  CollapsibleRootProps,
  CollapsibleRootState,
  CollapsibleTriggerProps,
  CollapsibleTriggerState,
  CollapsiblePanelProps,
  CollapsiblePanelState,
} from './collapsible'
export type {
  AccordionRootChangeEventDetails,
  AccordionRootChangeEventReason,
  AccordionRootContextValue,
  AccordionRootProps,
  AccordionRootState,
  AccordionValue,
  AccordionItemChangeEventDetails,
  AccordionItemChangeEventReason,
  AccordionItemContextValue,
  AccordionItemProps,
  AccordionItemState,
  AccordionHeaderProps,
  AccordionHeaderState,
  AccordionTriggerProps,
  AccordionTriggerState,
  AccordionPanelProps,
  AccordionPanelState,
} from './accordion'
export type {
  TabsRootChangeEventDetails,
  TabsRootChangeEventReason,
  TabsRootContextValue,
  TabsRootProps,
  TabsRootState,
  TabsValue,
  TabsListProps,
  TabsListState,
  TabsListContextValue,
  TabsActivationDirection,
  TabTriggerMetadata,
  TabsIndicatorPosition,
  TabTriggerProps,
  TabsIndicatorSize,
  TabTriggerState,
  TabsPanelProps,
  TabsPanelState,
  TabsIndicatorProps,
  TabsIndicatorState,
} from './tabs'
export type {
  ProgressRootContextValue,
  ProgressRootProps,
  ProgressRootState,
  ProgressStatus,
  ProgressTrackProps,
  ProgressTrackState,
  ProgressIndicatorProps,
  ProgressIndicatorState,
  ProgressLabelProps,
  ProgressLabelState,
  ProgressValueProps,
  ProgressValueState,
} from './progress'
export type {
  MeterRootContextValue,
  MeterRootProps,
  MeterRootState,
  MeterTrackProps,
  MeterTrackState,
  MeterIndicatorProps,
  MeterIndicatorState,
  MeterLabelProps,
  MeterLabelState,
  MeterValueProps,
  MeterValueState,
} from './meter'
export type {
  AvatarRootContextValue,
  AvatarRootProps,
  AvatarRootState,
  ImageLoadingStatus,
  AvatarImageProps,
  AvatarImageState,
  AvatarFallbackProps,
  AvatarFallbackState,
} from './avatar'
export type {
  ScrollAreaRootContextValue,
  ScrollAreaRootRefs,
  ScrollAreaRootProps,
  ScrollAreaRootState,
  HiddenState,
  OverflowEdges,
  Size,
  Coords,
  ScrollAreaViewportProps,
  ScrollAreaViewportState,
  ScrollAreaViewportContextValue,
  ScrollAreaScrollbarProps,
  ScrollAreaScrollbarState,
  ScrollAreaScrollbarOrientation,
  ScrollAreaContentProps,
  ScrollAreaContentState,
  ScrollAreaThumbProps,
  ScrollAreaThumbState,
  ScrollAreaCornerProps,
  ScrollAreaCornerState,
} from './scroll-area'
export type {
  PortalProps,
  PortalState,
  PortalContextValue,
  PortalFocusManagerState,
  PortalContainer,
  PortalContainerProp,
} from './portal'
export type {
  FieldRootProps,
  FieldRootState,
  FieldRootActions,
  FieldValidityData,
  FieldLabelProps,
  FieldLabelState,
  FieldDescriptionProps,
  FieldDescriptionState,
  FieldErrorProps,
  FieldErrorState,
  FieldControlProps,
  FieldControlState,
  FieldControlChangeEventDetails,
  FieldControlChangeEventReason,
  FieldValidityProps,
  FieldValidityState,
  FieldItemProps,
  FieldItemState,
  FieldItemContextValue,
} from './field'
export type {
  Errors,
  ValidationMode,
  FormValues,
  FormContextValue,
  FormFieldRegistration,
} from './internals/form-context'
export type {
  LabelableContextValue,
  LabelableProviderProps,
  CreateLabelParameters,
  CreateLabelReturnValue,
  CreateLabelableIdParameters,
} from './internals/labelable-provider'
export type { FieldRootContextValue } from './internals/field-root-context'
export type {
  FieldsetRootProps,
  FieldsetRootState,
  FieldsetRootContextValue,
  FieldsetLegendProps,
  FieldsetLegendState,
} from './fieldset'
export type {
  FormProps,
  FormState,
  FormActions,
  FormSubmitEventDetails,
  FormSubmitEventReason,
} from './form'
export type {
  DialogRootProps,
  DialogRootActions,
  DialogRootChangeEventDetails,
  DialogRootChangeEventReason,
  DialogRootContextValue,
  DialogTriggerProps,
  DialogTriggerState,
  DialogPortalProps,
  DialogBackdropProps,
  DialogBackdropState,
  DialogViewportProps,
  DialogViewportState,
  DialogPopupProps,
  DialogPopupState,
  DialogTitleProps,
  DialogTitleState,
  DialogDescriptionProps,
  DialogDescriptionState,
  DialogCloseProps,
  DialogCloseState,
} from './dialog'
export type {
  AlertDialogRootProps,
  AlertDialogRootActions,
  AlertDialogRootChangeEventDetails,
  AlertDialogRootChangeEventReason,
  AlertDialogRootContextValue,
  AlertDialogTriggerProps,
  AlertDialogTriggerState,
  AlertDialogPortalProps,
  AlertDialogBackdropProps,
  AlertDialogBackdropState,
  AlertDialogViewportProps,
  AlertDialogViewportState,
  AlertDialogPopupProps,
  AlertDialogPopupState,
  AlertDialogTitleProps,
  AlertDialogTitleState,
  AlertDialogDescriptionProps,
  AlertDialogDescriptionState,
  AlertDialogCloseProps,
  AlertDialogCloseState,
} from './alert-dialog'
export type {
  PopoverRootProps,
  PopoverRootActions,
  PopoverRootChangeEventDetails,
  PopoverRootChangeEventReason,
  PopoverRootContextValue,
  PopoverTriggerProps,
  PopoverTriggerState,
  PopoverPortalProps,
  PopoverPositionerProps,
  PopoverPositionerState,
  PopoverPositionerContextValue,
  Side,
  Align,
  PopoverPopupProps,
  PopoverPopupState,
  PopoverArrowProps,
  PopoverArrowState,
  PopoverBackdropProps,
  PopoverBackdropState,
  PopoverTitleProps,
  PopoverTitleState,
  PopoverDescriptionProps,
  PopoverDescriptionState,
  PopoverCloseProps,
  PopoverCloseState,
  PopoverViewportProps,
  PopoverViewportState,
} from './popover'
export type {
  InputProps,
  InputState,
  InputChangeEventDetails,
  InputChangeEventReason,
} from './input'
export type {
  CreateControlledOptions,
  ControlledSetter,
  ControlledSignal,
  BaseUIChangeEventDetails,
  BaseUIGenericEventDetails,
  ChangeEventReason,
  CreateRenderOptions,
  RenderProp,
  RenderFunction,
  PolymorphicProps,
  NativeProps,
  RenderFn,
  UseRenderOptions,
  UseButtonParameters,
  UseButtonReturnValue,
  UseFocusableWhenDisabledParameters,
  UseFocusableWhenDisabledReturnValue,
  UseFloatingOptions,
  UseFloatingReturn,
  FloatingStyles,
  Placement,
  Strategy,
  Middleware,
  FocusTrapOptions,
  DismissOptions,
  TextDirection,
  DirectionProviderProps,
  DirectionContextValue,
} from './internals'
