export { TabsRoot as Root } from './root/TabsRoot'
export { TabsList as List } from './list/TabsList'
export { TabTrigger as Trigger } from './trigger/TabTrigger'
export { TabsPanel as Panel } from './panel/TabsPanel'
export { TabsIndicator as Indicator } from './indicator/TabsIndicator'
